<a href="https://colab.research.google.com/github/VishalMoradia/ML-Practice/blob/main/ClassifierMetrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('/heart-disease.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [2]:
X = df.drop('target', axis =1)
y = df['target']

# we do not have to import train_test_split as we are using cross_validation here.

model = RandomForestClassifier(n_estimators=100)


In [3]:
# cross validation accuracy 

cv_acc = cross_val_score(model, X, y, cv=5, scoring=None)

# if scoring is set equal to none then model's default scoring evaluation metric is used. (Accuracy for classification model)

cv_acc



array([0.80327869, 0.8852459 , 0.80327869, 0.8       , 0.76666667])

In [4]:
#cross validated accuracy 

print(f"the cross validated accuracy is: {np.mean(cv_acc)*100:2f}%")

the cross validated accuracy is: 81.169399%


In [7]:
cv_precision = cross_val_score(model, X, y, cv =5, scoring = "precision")
cv_precision

array([0.8       , 0.90625   , 0.8125    , 0.78787879, 0.76315789])

In [8]:
print(f"the cross validated accuracy is: {np.mean(cv_precision)*100:2f}%")

the cross validated accuracy is: 81.395734%


In [10]:
cv_recall = cross_val_score(model, X, y, cv =5, scoring = "recall")
cv_recall

array([0.84848485, 0.87878788, 0.78787879, 0.78787879, 0.87878788])

In [11]:
print(f"the cross validated accuracy is: {np.mean(cv_recall)*100:2f}%")

the cross validated accuracy is: 83.636364%


In [12]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split


X = df.drop('target', axis =1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

# we do not have to import train_test_split as we are using cross_validation here.

model = RandomForestClassifier(n_estimators=100)

model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8360655737704918

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X = df.drop('target', axis =1)
y = df['target']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


model = RandomForestRegressor(n_estimators=100)

model.fit(X_train, y_train)

In [15]:
accuracy_score(y_test, model.predict(X_test))

0.8529411764705882

In [16]:
recall_score(y_test, model.predict(X_test))

0.90625

In [17]:
precision_score(y_test, model.predict(X_test))

0.8055555555555556

In [18]:
f1_score(y_test, model.predict(X_test))

0.8529411764705882